version: '3.7'
services:
  web:
    image: nginx:alpine
    container_name: server_1
    ports:
      - "8000:80"
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - default
  web_1:
     image: nginx:alpine
     container_name: server_2
     ports:
       - "8001:80"
     volumes:
       - ./app:/usr/share/nginx/html     
     networks:
       - default
  web_2:
      image: php:8.3.6-apache
      container_name: server_3
      ports:
       - "8002:80"
      volumes:
        - ./wordpress:/var/www/html
      networks:
        default:
          name: unc-network
          driver: bridge
          external: false
        conakry:
          external: true
   wp:
       image: wordpress:php8.3-apache
       ports:
         - 8092: 80
       environment:
         WORDPRESS_DB_HOST: db
         WORDPRESS_DB_USER: wp_user
         WORDPRESS_DB_PASSWORD: password
         WORDPRESS_DB_NAME: wp_database
       networks:
         - default
       depends_on:
         - db
    db:
       image: mysql:8.3.0
       container_name: db_wordpress
       environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=wp_database
         - MYSQL_USER=wp_user
         - MYSQL_PASSWORD=password
       networks:
         - default

      
         
   
