version: '3.7'
services:
  web:
    image: nginx:alpine
    container_name: server_1
    ports:
      - "8000:80"
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - default
  web_1:
     image: nginx:alpine
     container_name: server_2
     ports:
       - "8001:80"
     volumes:
       - ./app:/usr/share/nginx/html     
     networks:
       - default
  web_2:
      image: php:8.3.6-apache
      container_name: server_3
      ports:
       - "8002:80"
      volumes:
        - ./wordpress:/var/www/html
      networks:
        default:
          name: unc-network
          driver: bridge
          external: false
        conakry:
          external: true
 

      
         
   
